### PR TITLE
Add app icon - Android and iOS

### PR DESCRIPTION
**Pull request by arctouch-vivyanrodrigues**
Add app icon on Android and iOS

### CODE REVIEW

**Review by arctouch-victorbotamedi — CHANGES_REQUESTED** [review]
Can we have adaptive icons for Android?

**Comment by arctouch-vivyanrodrigues** [comment]
> Can we have adaptive icons for Android?

Done. Can you check now?

**Comment by arctouch-vivyanrodrigues** [comment]
Screen Shot 2021-06-30 at 18 59 01
Screen Shot 2021-06-30 at 19 02 48

**Comment by arctouch-victorbotamedi** [comment]
There are a lot of build files on the PR, can you check the `.gitignore` and also delete the files from git?

**Comment by arctouch-victorbotamedi** [comment]
Also, I'm not seeing the iOS icons on the diff, did add for all resolutions?

**Comment by arctouch-vivyanrodrigues** [comment]
Done! Can you check now?

**Review by arctouch-victorbotamedi — APPROVED** [review]

**Pull request merged**
